name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build and push the Docker image
      run: |
        docker build . --file ./sample-packages/docker/Dockerfile --tag my-image-name:$(date +%s)
        echo $GITHUB_TOKEN | docker login ghcr.io -u amadub --password-stdin
        docker tag IMAGE_ID ghcr.io/amadub/my-image-name:latest
        docker push ghcr.io/amadub/my-image-name:latest
